// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtXIe3jxFqeZ3rpQhwL7WkWkkqSu25ORQ',
    appId: '1:715562519142:web:e61652627425fe1d057ba7',
    messagingSenderId: '715562519142',
    projectId: 'erupaiya-f9411',
    authDomain: 'erupaiya-f9411.firebaseapp.com',
    storageBucket: 'erupaiya-f9411.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdEhBeVZUgoAiqKcDhgD0slpa6xbo9B7w',
    appId: '1:715562519142:android:6f7b93fa749fe881057ba7',
    messagingSenderId: '715562519142',
    projectId: 'erupaiya-f9411',
    storageBucket: 'erupaiya-f9411.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiq14eq-fCDxIM_T1DDyJnTc5OGRyL7e4',
    appId: '1:715562519142:ios:e31dc95aa24f8ee7057ba7',
    messagingSenderId: '715562519142',
    projectId: 'erupaiya-f9411',
    storageBucket: 'erupaiya-f9411.firebasestorage.app',
    iosBundleId: 'com.innoplix.erupaiya',
  );
}
